
palette = "tokyonight"

# Setups
right_format = "$cmd_duration"
# format = """$directory$git_branch$git_status\n$character"""
format = """$directory$git_branch\n$character"""
add_newline = false
command_timeout = 1000


c.disabled = true
cmake.disabled = true
haskell.disabled = true
ruby.disabled = true
package.disabled = true
lua.disabled = true


[character]
success_symbol = "[](blue bold)"
error_symbol = "[](red)"
# vicmd_symbol = "[](green)"


[directory]
style = "bold fg:black bg:none"
format = "[]($style)[ ](bg:black fg:cyan)[ $path](bg:black fg:blue bold)[ ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"repos" = " "

[git_branch]
style = "bg:none fg:black"
format = "[]($style)[[  ](bg:black fg:green bold)$branch ](bg:black fg:blue)[ ]($style)"
# symbol = ""
# format = '[[ $symbol $branch ](fg:#a9b1d6 bg:#414868)]($style)'

[git_status]
style = "bg:none fg:black"
format = "[]($style)[ $all_status$ahead_behind](bg:black fg:yellow)[ ]($style)"
conflicted = "="
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
up_to_date = ""
untracked = "?${count} "
stashed = " "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "${count} "

[cmd_duration]
min_time = 1
# duration & style 
format = "[]($style)[[ ](bg:black fg:yellow bold)$duration](bg:black fg:white)[ ]($style)"
disabled = false
style = "bg:none fg:black"

[nodejs]
symbol = ""
style = "bg:#24283b"
format = '[[ $symbol ($version) ](fg:green bg:#24283b)]($style)'

[rust]
symbol = ""
style = "bg:#24283b"
format = '[[ $symbol ($version) ](fg:yellow bg:#24283b)]($style)'

[golang]
symbol = ""
style = "bg:#24283b"
format = '[[ $symbol ($version) ](fg:blue bg:#24283b)]($style)'

[time]
disabled = true
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[palettes.tokyonight]
black = "#2e3c64"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
purple = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"
